#!/usr/bin/env bash
set -euo pipefail

fail() {
  echo "[eona-mcp bootstrap] ERROR: $*" >&2
  exit 1
}

log() {
  printf '[eona-mcp bootstrap] %s\n' "$*" >&2
}

usage() {
  cat >&2 <<'EOF'
Usage: bootstrap.sh [options]

Installs the EONA MCP surface and provisions the sibling sealed EONA CLI runtime.

Options:
  --family-root DIR        EONA family root. Defaults to ~/.eona.
  --install-dir DIR        MCP install root. Defaults to <family-root>/eona-mcp.
  --cli-install-dir DIR    CLI install root. Defaults to <family-root>/eona-cli.
  --workspace-dir DIR      Shared workspace. Defaults to <family-root>/workspace.
  --cli-bootstrap-url URL  CLI bootstrap URL. Defaults to https://cli.eona.dev/bootstrap.sh.
  --cli-version VERSION    Pass a specific CLI version to the CLI bootstrap.
  --cli-artifact-url URL   Pass a CLI artifact base URL to the CLI bootstrap.
  --repair-cli             Run the CLI bootstrap even when bin/eona already exists.
  --skip-cli               Install only the MCP surface.
  -h, --help               Show this help.
EOF
}

shell_quote() {
  local quoted
  printf -v quoted '%q' "$1"
  printf '%s\n' "$quoted"
}

copy_path() {
  local source_root="$1"
  local install_dir="$2"
  local relpath="$3"
  [[ -e "${source_root}/${relpath}" ]] || return 0
  rm -rf "${install_dir}/${relpath}"
  mkdir -p "$(dirname "${install_dir}/${relpath}")"
  cp -a "${source_root}/${relpath}" "${install_dir}/${relpath}"
}

install_mcp_surface() {
  local source_root="$1"
  local install_dir="$2"
  [[ -f "${source_root}/pyproject.toml" ]] || fail "source root missing pyproject.toml: ${source_root}"
  [[ -d "${source_root}/src/eona_mcp" ]] || fail "source root missing src/eona_mcp: ${source_root}"

  mkdir -p "$install_dir"
  for relpath in \
    agent \
    bin \
    contracts \
    src \
    AGPL_NETWORK_SOURCE_NOTICE.md \
    LICENSE \
    LICENSES \
    README.md \
    pyproject.toml; do
    copy_path "$source_root" "$install_dir" "$relpath"
  done
  printf 'eona-mcp\n' >"${install_dir}/.eona-mcp-product"
}

write_env_file() {
  local install_dir="$1"
  local family_root="$2"
  local cli_install_dir="$3"
  local workspace_dir="$4"
  local env_file="${install_dir}/eona-mcp.env"

  cat >"$env_file" <<EOF
# Generated by EONA MCP bootstrap.
export EONA_FAMILY_ROOT=$(shell_quote "$family_root")
export EONA_MCP_INSTALL_ROOT=$(shell_quote "$install_dir")
export EONA_CLI_INSTALL_ROOT=$(shell_quote "$cli_install_dir")
export EONA_MCP_WORKSPACE=$(shell_quote "$workspace_dir")
export EONA_CLI=$(shell_quote "${cli_install_dir%/}/bin/eona")
EOF
}

provision_cli() {
  local cli_install_dir="$1"
  local cli_bootstrap_url="$2"
  local cli_version="$3"
  local cli_artifact_url="$4"

  command -v curl >/dev/null 2>&1 || fail "curl is required to provision eona-cli"
  local args=()
  if [[ -n "$cli_version" ]]; then
    args+=(--version "$cli_version")
  fi
  if [[ -n "$cli_artifact_url" ]]; then
    args+=(--artifact-url "$cli_artifact_url")
  fi
  args+=("$cli_install_dir")
  curl -sSL "$cli_bootstrap_url" | sh -s -- "${args[@]}"
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
FAMILY_ROOT="${EONA_FAMILY_ROOT:-${HOME}/.eona}"
MCP_INSTALL_DIR="${EONA_MCP_INSTALL_ROOT:-}"
CLI_INSTALL_DIR="${EONA_CLI_INSTALL_ROOT:-}"
WORKSPACE_DIR="${EONA_MCP_WORKSPACE:-}"
CLI_BOOTSTRAP_URL="${EONA_CLI_BOOTSTRAP_URL:-https://cli.eona.dev/bootstrap.sh}"
CLI_VERSION="${EONA_CLI_BOOTSTRAP_VERSION:-}"
CLI_ARTIFACT_URL="${EONA_CLI_ARTIFACT_URL:-}"
REPAIR_CLI=0
SKIP_CLI=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --family-root)
      [[ $# -ge 2 ]] || fail "missing value for --family-root"
      FAMILY_ROOT="$2"
      shift 2
      ;;
    --install-dir|--mcp-install-dir)
      [[ $# -ge 2 ]] || fail "missing value for $1"
      MCP_INSTALL_DIR="$2"
      shift 2
      ;;
    --cli-install-dir)
      [[ $# -ge 2 ]] || fail "missing value for --cli-install-dir"
      CLI_INSTALL_DIR="$2"
      shift 2
      ;;
    --workspace-dir)
      [[ $# -ge 2 ]] || fail "missing value for --workspace-dir"
      WORKSPACE_DIR="$2"
      shift 2
      ;;
    --cli-bootstrap-url)
      [[ $# -ge 2 ]] || fail "missing value for --cli-bootstrap-url"
      CLI_BOOTSTRAP_URL="$2"
      shift 2
      ;;
    --cli-version)
      [[ $# -ge 2 ]] || fail "missing value for --cli-version"
      CLI_VERSION="$2"
      shift 2
      ;;
    --cli-artifact-url)
      [[ $# -ge 2 ]] || fail "missing value for --cli-artifact-url"
      CLI_ARTIFACT_URL="$2"
      shift 2
      ;;
    --repair-cli)
      REPAIR_CLI=1
      shift
      ;;
    --skip-cli)
      SKIP_CLI=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --*)
      fail "unsupported option: $1"
      ;;
    *)
      fail "unexpected argument: $1"
      ;;
  esac
done

FAMILY_ROOT="$(mkdir -p "$FAMILY_ROOT" && cd "$FAMILY_ROOT" && pwd -P)"
MCP_INSTALL_DIR="${MCP_INSTALL_DIR:-${FAMILY_ROOT}/eona-mcp}"
CLI_INSTALL_DIR="${CLI_INSTALL_DIR:-${FAMILY_ROOT}/eona-cli}"
WORKSPACE_DIR="${WORKSPACE_DIR:-${FAMILY_ROOT}/workspace}"

mkdir -p "$WORKSPACE_DIR"
WORKSPACE_DIR="$(cd "$WORKSPACE_DIR" && pwd -P)"
mkdir -p "$(dirname "$MCP_INSTALL_DIR")" "$(dirname "$CLI_INSTALL_DIR")"

install_mcp_surface "$SOURCE_ROOT" "$MCP_INSTALL_DIR"
MCP_INSTALL_DIR="$(cd "$MCP_INSTALL_DIR" && pwd -P)"
write_env_file "$MCP_INSTALL_DIR" "$FAMILY_ROOT" "$CLI_INSTALL_DIR" "$WORKSPACE_DIR"

if [[ "$SKIP_CLI" -eq 1 ]]; then
  log "Skipped eona-cli provisioning"
elif [[ -x "${CLI_INSTALL_DIR%/}/bin/eona" && "$REPAIR_CLI" -ne 1 ]]; then
  log "Using existing eona-cli at ${CLI_INSTALL_DIR%/}/bin/eona"
else
  log "Provisioning eona-cli into ${CLI_INSTALL_DIR}"
  provision_cli "$CLI_INSTALL_DIR" "$CLI_BOOTSTRAP_URL" "$CLI_VERSION" "$CLI_ARTIFACT_URL"
fi

log "Installed EONA MCP to ${MCP_INSTALL_DIR}"
log "Workspace: ${WORKSPACE_DIR}"
log "Run: ${MCP_INSTALL_DIR}/bin/eona-mcp"
