#!/usr/bin/env bash
set -euo pipefail

fail() {
  echo "[eona-mcp bootstrap] ERROR: $*" >&2
  exit 1
}

log() {
  printf '[eona-mcp bootstrap] %s\n' "$*" >&2
}

usage() {
  cat >&2 <<'EOF'
Usage: bootstrap.sh [options]

Installs the EONA MCP surface and provisions the sibling sealed EONA CLI runtime.

Options:
  --family-root DIR        EONA family root. Defaults to ~/.eona.
  --install-dir DIR        MCP install root. Defaults to <family-root>/eona-mcp.
  --cli-install-dir DIR    CLI install root. Defaults to <family-root>/eona-cli.
  --workspace-dir DIR      Shared workspace. Defaults to <family-root>/workspace.
  --cli-bootstrap-url URL  CLI bootstrap URL. Defaults to https://cli.eona.dev/bootstrap.sh.
  --cli-version VERSION    Pass a specific CLI version to the CLI bootstrap.
  --cli-artifact-url URL   Pass a CLI artifact base URL to the CLI bootstrap.
  --repair-cli             Run the CLI bootstrap even when bin/eona already exists.
  --allow-cli-downgrade    Allow repair to replace a newer local CLI with the
                           requested bootstrap version.
  --skip-cli               Install only the MCP surface.
  -h, --help               Show this help.
EOF
}

shell_quote() {
  local quoted
  printf -v quoted '%q' "$1"
  printf '%s\n' "$quoted"
}

json_field() {
  local json_path="$1"
  local field="$2"
  perl -MJSON::PP - "$json_path" "$field" <<'PERL'
my ($path, $field) = @ARGV;
open my $fh, '<', $path or exit 1;
my $raw = do { local $/; <$fh> };
close $fh;
my $payload = eval { JSON::PP::decode_json($raw) } or exit 1;
my @parts = split /\./, $field;
my $value = $payload;
for my $part (@parts) {
    exit 1 unless ref($value) eq 'HASH' && exists $value->{$part};
    $value = $value->{$part};
}
exit 1 if ref($value) || !defined($value);
print $value;
PERL
}

copy_path() {
  local source_root="$1"
  local install_dir="$2"
  local relpath="$3"
  [[ -e "${source_root}/${relpath}" ]] || return 0
  rm -rf "${install_dir}/${relpath}"
  mkdir -p "$(dirname "${install_dir}/${relpath}")"
  cp -a "${source_root}/${relpath}" "${install_dir}/${relpath}"
}

install_mcp_surface() {
  local source_root="$1"
  local install_dir="$2"
  [[ -f "${source_root}/pyproject.toml" ]] || fail "source root missing pyproject.toml: ${source_root}"
  [[ -d "${source_root}/src/eona_mcp" ]] || fail "source root missing src/eona_mcp: ${source_root}"

  mkdir -p "$install_dir"
  for relpath in \
    agent \
    bin \
    contracts \
    src \
    AGPL_NETWORK_SOURCE_NOTICE.md \
    LICENSE \
    LICENSES \
    README.md \
    pyproject.toml; do
    copy_path "$source_root" "$install_dir" "$relpath"
  done
  printf 'eona-mcp\n' >"${install_dir}/.eona-mcp-product"
}

write_env_file() {
  local install_dir="$1"
  local family_root="$2"
  local cli_install_dir="$3"
  local workspace_dir="$4"
  local env_file="${install_dir}/eona-mcp.env"

  cat >"$env_file" <<EOF
# Generated by EONA MCP bootstrap.
export EONA_FAMILY_ROOT=$(shell_quote "$family_root")
export EONA_MCP_INSTALL_ROOT=$(shell_quote "$install_dir")
export EONA_CLI_INSTALL_ROOT=$(shell_quote "$cli_install_dir")
export EONA_MCP_WORKSPACE=$(shell_quote "$workspace_dir")
export EONA_CLI=$(shell_quote "${cli_install_dir%/}/bin/eona")
EOF
}

provision_cli() {
  local cli_install_dir="$1"
  local cli_bootstrap_url="$2"
  local cli_version="$3"
  local cli_artifact_url="$4"

  command -v curl >/dev/null 2>&1 || fail "curl is required to provision eona-cli"
  local args=()
  if [[ -n "$cli_version" ]]; then
    args+=(--version "$cli_version")
  fi
  if [[ -n "$cli_artifact_url" ]]; then
    args+=(--artifact-url "$cli_artifact_url")
  fi
  args+=("$cli_install_dir")
  curl -sSL "$cli_bootstrap_url" | sh -s -- "${args[@]}"
}

cli_version() {
  local executable="$1"
  "$executable" --version 2>/dev/null | awk '{print $NF}' | head -n 1
}

version_gt() {
  local left="$1"
  local right="$2"
  [[ -n "$left" && -n "$right" ]] || return 1
  awk -v left="$left" -v right="$right" '
    function normalize(value) {
      sub(/^[^0-9]*/, "", value)
      sub(/[^0-9.].*$/, "", value)
      return value
    }
    BEGIN {
      left = normalize(left)
      right = normalize(right)
      split(left, l, ".")
      split(right, r, ".")
      for (i = 1; i <= 4; i++) {
        lv = (l[i] == "" ? 0 : l[i]) + 0
        rv = (r[i] == "" ? 0 : r[i]) + 0
        if (lv > rv) exit 0
        if (lv < rv) exit 1
      }
      exit 1
    }
  '
}

version_lt() {
  local left="$1"
  local right="$2"
  version_gt "$right" "$left"
}

guard_cli_repair_version() {
  local executable="$1"
  local target_version="$2"
  local allow_downgrade="$3"
  [[ -x "$executable" ]] || return 0
  [[ "$allow_downgrade" -eq 0 ]] || return 0

  local current_version
  current_version="$(cli_version "$executable")"
  if version_gt "$current_version" "$target_version"; then
    fail "refusing to replace newer eona-cli ${current_version} with bootstrap target ${target_version}; pass --allow-cli-downgrade to override"
  fi
}

cli_needs_upgrade() {
  local executable="$1"
  local min_version="$2"
  [[ -x "$executable" ]] || return 0

  local current_version
  current_version="$(cli_version "$executable")"
  [[ -n "$current_version" ]] || return 0
  version_lt "$current_version" "$min_version"
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CLI_DEPENDENCY_CONTRACT="${SOURCE_ROOT}/contracts/eona-cli-dependency.json"
DEFAULT_CLI_BOOTSTRAP_VERSION="$(json_field "$CLI_DEPENDENCY_CONTRACT" compatibility.min_version)" || fail "dependency contract missing compatibility.min_version"
FAMILY_ROOT="${EONA_FAMILY_ROOT:-${HOME}/.eona}"
MCP_INSTALL_DIR="${EONA_MCP_INSTALL_ROOT:-}"
CLI_INSTALL_DIR="${EONA_CLI_INSTALL_ROOT:-}"
WORKSPACE_DIR="${EONA_MCP_WORKSPACE:-}"
CLI_BOOTSTRAP_URL="${EONA_CLI_BOOTSTRAP_URL:-https://cli.eona.dev/bootstrap.sh}"
CLI_VERSION="${EONA_CLI_BOOTSTRAP_VERSION:-$DEFAULT_CLI_BOOTSTRAP_VERSION}"
CLI_ARTIFACT_URL="${EONA_CLI_ARTIFACT_URL:-}"
REPAIR_CLI=0
ALLOW_CLI_DOWNGRADE=0
SKIP_CLI=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --family-root)
      [[ $# -ge 2 ]] || fail "missing value for --family-root"
      FAMILY_ROOT="$2"
      shift 2
      ;;
    --install-dir|--mcp-install-dir)
      [[ $# -ge 2 ]] || fail "missing value for $1"
      MCP_INSTALL_DIR="$2"
      shift 2
      ;;
    --cli-install-dir)
      [[ $# -ge 2 ]] || fail "missing value for --cli-install-dir"
      CLI_INSTALL_DIR="$2"
      shift 2
      ;;
    --workspace-dir)
      [[ $# -ge 2 ]] || fail "missing value for --workspace-dir"
      WORKSPACE_DIR="$2"
      shift 2
      ;;
    --cli-bootstrap-url)
      [[ $# -ge 2 ]] || fail "missing value for --cli-bootstrap-url"
      CLI_BOOTSTRAP_URL="$2"
      shift 2
      ;;
    --cli-version)
      [[ $# -ge 2 ]] || fail "missing value for --cli-version"
      CLI_VERSION="$2"
      shift 2
      ;;
    --cli-artifact-url)
      [[ $# -ge 2 ]] || fail "missing value for --cli-artifact-url"
      CLI_ARTIFACT_URL="$2"
      shift 2
      ;;
    --repair-cli)
      REPAIR_CLI=1
      shift
      ;;
    --allow-cli-downgrade)
      ALLOW_CLI_DOWNGRADE=1
      shift
      ;;
    --skip-cli)
      SKIP_CLI=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --*)
      fail "unsupported option: $1"
      ;;
    *)
      fail "unexpected argument: $1"
      ;;
  esac
done

FAMILY_ROOT="$(mkdir -p "$FAMILY_ROOT" && cd "$FAMILY_ROOT" && pwd -P)"
MCP_INSTALL_DIR="${MCP_INSTALL_DIR:-${FAMILY_ROOT}/eona-mcp}"
CLI_INSTALL_DIR="${CLI_INSTALL_DIR:-${FAMILY_ROOT}/eona-cli}"
WORKSPACE_DIR="${WORKSPACE_DIR:-${FAMILY_ROOT}/workspace}"

mkdir -p "$WORKSPACE_DIR"
WORKSPACE_DIR="$(cd "$WORKSPACE_DIR" && pwd -P)"
mkdir -p "$(dirname "$MCP_INSTALL_DIR")" "$(dirname "$CLI_INSTALL_DIR")"

install_mcp_surface "$SOURCE_ROOT" "$MCP_INSTALL_DIR"
MCP_INSTALL_DIR="$(cd "$MCP_INSTALL_DIR" && pwd -P)"
write_env_file "$MCP_INSTALL_DIR" "$FAMILY_ROOT" "$CLI_INSTALL_DIR" "$WORKSPACE_DIR"

CLI_EXECUTABLE="${CLI_INSTALL_DIR%/}/bin/eona"

if [[ "$SKIP_CLI" -eq 1 ]]; then
  log "Skipped eona-cli provisioning"
elif [[ -x "$CLI_EXECUTABLE" && "$REPAIR_CLI" -ne 1 ]] && ! cli_needs_upgrade "$CLI_EXECUTABLE" "$DEFAULT_CLI_BOOTSTRAP_VERSION"; then
  log "Using existing eona-cli at ${CLI_EXECUTABLE}"
else
  log "Provisioning eona-cli into ${CLI_INSTALL_DIR}"
  guard_cli_repair_version "$CLI_EXECUTABLE" "$CLI_VERSION" "$ALLOW_CLI_DOWNGRADE"
  provision_cli "$CLI_INSTALL_DIR" "$CLI_BOOTSTRAP_URL" "$CLI_VERSION" "$CLI_ARTIFACT_URL"
fi

log "Installed EONA MCP to ${MCP_INSTALL_DIR}"
log "Workspace: ${WORKSPACE_DIR}"
log "Run: ${MCP_INSTALL_DIR}/bin/eona-mcp"
