# SPDX-License-Identifier: GPL-3.0-or-later
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shlex
import sys
from pathlib import Path
from typing import TextIO

from .cli import EonaCliInvocationError, EonaCliRunner
from .config import EonaMcpConfigError, load_config


DEFAULT_SESSION_ID = "default_session"
_PROJECT_SOURCES_HEADER_PRINTED = False
PROJECT_ENV_KEYS = (
    "EONA_PROJECT_ID",
    "EONA_SESSION_ID",
    "EONA_PROJECT_DESCRIPTION",
    "EONA_SOURCES_JSON",
    "EONA_SOURCE_ROOTS_JSON",
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Configure and prepare a local EONA stdio MCP project.")
    parser.add_argument("--install-root", help="Bootstrap install root that should contain eona-mcp.env.")
    parser.add_argument("--env-file", help="Optional env file path. Defaults to <install-root>/eona-mcp.env.")
    parser.add_argument("--skip-prepare", action="store_true", help="Write project env but do not run EONA add.")
    parser.add_argument("--prepare-only", action="store_true", help="Prepare project sources without writing an env file.")
    parser.add_argument("--marker-dir", help="Optional directory for successful prepare markers.")
    args = parser.parse_args(argv)

    if not args.prepare_only and not args.install_root:
        parser.error("--install-root is required unless --prepare-only is set.")
    install_root = Path(args.install_root).expanduser().resolve() if args.install_root else None
    env_file = (
        Path(args.env_file).expanduser().resolve()
        if args.env_file
        else (install_root / "eona-mcp.env" if install_root is not None else None)
    )
    try:
        project_env = resolve_project_env(stdin=sys.stdin, stderr=sys.stderr)
        should_prepare = not args.skip_prepare and _parse_bool(os.environ.get("EONA_MCP_PREPARE", "1"))
        if should_prepare:
            prepare_project(
                project_env,
                marker_dir=Path(args.marker_dir).expanduser().resolve() if args.marker_dir else None,
                install_root=install_root,
                stdin=sys.stdin,
                stderr=sys.stderr,
            )
        else:
            _log({"ok": True, "operation": "mcp_prepare", "summary": "Skipped project preparation."})
        if env_file is not None and not args.prepare_only:
            write_env_file(env_file, project_env)
    except (EonaMcpConfigError, EonaCliInvocationError, RuntimeError, ValueError) as exc:
        payload: dict[str, object] = {"ok": False, "operation": "mcp_prepare", "summary": str(exc)}
        if isinstance(exc, EonaCliInvocationError):
            payload.update({"returncode": exc.returncode, "stdout": exc.stdout, "stderr": exc.stderr})
        _log(payload)
        if not _parse_bool(os.environ.get("EONA_STARTUP_REQUIRED", "1")):
            return 0
        return getattr(exc, "returncode", 1) or 1
    return 0


def resolve_project_env(*, stdin: TextIO, stderr: TextIO) -> dict[str, str]:
    project_id = os.environ.get("EONA_PROJECT_ID", "").strip()
    session_id = os.environ.get("EONA_SESSION_ID", "").strip() or DEFAULT_SESSION_ID
    description = os.environ.get("EONA_PROJECT_DESCRIPTION", "").strip()
    sources_json = os.environ.get("EONA_SOURCES_JSON", "").strip()
    source_roots_json = os.environ.get("EONA_SOURCE_ROOTS_JSON", "").strip()

    if not sources_json:
        if not stdin.isatty():
            sources_json = "[]"
        else:
            print("EONA MCP project setup", file=stderr)
            if not project_id:
                project_id = input("Project ID [default]: ").strip() or "default"
            if not description:
                description = input("Project description (optional): ").strip()
            sources: list[str] = []
            while True:
                source = input("Photo source path (blank to finish): ").strip()
                if not source:
                    break
                sources.append(source)
            sources_json = json.dumps(sources, ensure_ascii=False)

    project_env = {
        "EONA_PROJECT_ID": project_id or "default",
        "EONA_SESSION_ID": session_id,
        "EONA_SOURCES_JSON": sources_json,
    }
    if description:
        project_env["EONA_PROJECT_DESCRIPTION"] = description
    if source_roots_json:
        project_env["EONA_SOURCE_ROOTS_JSON"] = source_roots_json

    # Validate before writing the env file.
    load_config(project_env)
    return project_env


def write_env_file(path: Path, project_env: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = _preserved_env_lines(path)
    if lines:
        lines.append("")
        lines.append("# EONA MCP project defaults.")
    else:
        lines = ["# Generated by EONA bootstrap for local stdio MCP."]
    for key in PROJECT_ENV_KEYS:
        value = project_env.get(key)
        if not value:
            continue
        lines.append(f'if [ -z "${{{key}:-}}" ]; then export {key}={shlex.quote(value)}; fi')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _preserved_env_lines(path: Path) -> list[str]:
    if not path.is_file():
        return []
    preserved: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line == "# EONA MCP project defaults.":
            continue
        if line == "# Generated by EONA bootstrap for local stdio MCP.":
            continue
        if any(key in line for key in PROJECT_ENV_KEYS):
            continue
        preserved.append(line)
    while preserved and not preserved[-1].strip():
        preserved.pop()
    return preserved


def prepare_project(
    project_env: dict[str, str],
    *,
    marker_dir: Path | None = None,
    install_root: Path | None = None,
    stdin: TextIO | None = None,
    stderr: TextIO | None = None,
) -> dict[str, object]:
    merged_env = dict(os.environ)
    merged_env.update(project_env)
    config = load_config(merged_env)
    marker = _prepare_marker_path(config, marker_dir=marker_dir)
    runner = EonaCliRunner(config)
    force_append = _parse_bool(os.environ.get("EONA_FORCE_APPEND", "0"))
    _log_prepare_environment(config)
    if not config.sources:
        current_source_roots = _existing_session_source_roots(runner)
        hint = ""
        if not current_source_roots:
            hint = "No source folders are attached.\nUse the MCP tools to append folders before running queries."
        payload: dict[str, object] = {
            "ok": True,
            "operation": "mcp_prepare",
            "status": "skipped",
            "skip_reason": "no_sources_configured",
            "project_id": config.project_id,
            "session_id": config.session_id,
            "sources": [],
            "source_roots": [],
            "summary": "Skipped source preparation because EONA_SOURCES_JSON was not provided. Runtime/bootstrap setup only.",
            "hint": hint,
        }
        payload["current_source_roots"] = current_source_roots
        _log(payload)
        return payload
    if marker is not None and marker.is_file() and not force_append:
        current_source_roots = _existing_session_source_roots(runner)
        payload: dict[str, object] = {
            "ok": True,
            "operation": "mcp_prepare",
            "project_id": config.project_id,
            "session_id": config.session_id,
            "sources": list(config.sources),
            "source_roots": list(config.source_roots),
            "summary": "Skipped project preparation; successful marker already exists.",
            "marker": str(marker),
        }
        payload["current_source_roots"] = current_source_roots
        _log(payload)
        return payload
    confirmation = _confirm_existing_source_roots(
        config=config,
        runner=runner,
        stdin=stdin or sys.stdin,
        stderr=stderr or sys.stderr,
    )
    if isinstance(confirmation, dict):
        confirmation["current_source_roots"] = list(confirmation.get("existing_source_roots") or [])
        marker = _prepare_skip_marker_path(config, install_root=install_root)
        if marker is not None:
            _write_prepare_marker(marker, confirmation)
            confirmation["skip_marker"] = str(marker)
        _log(confirmation)
        return confirmation
    try:
        result = runner.add(
            sources=config.sources,
            source_roots=config.source_roots,
            refresh=True,
            stream_stderr=True,
        )
    except EonaCliInvocationError:
        raise
    failed_sources = [
        source
        for source in (result.get("result") or {}).get("sources", [])
        if isinstance(source, dict) and source.get("ok") is False
    ]
    if result.get("ok") is False or failed_sources:
        raise RuntimeError(result.get("summary") or "EONA add reported failed source(s).")
    payload: dict[str, object] = {
        "ok": True,
        "operation": "mcp_prepare",
        "project_id": config.project_id,
        "session_id": config.session_id,
        "sources": list(config.sources),
        "source_roots": list(config.source_roots),
        **_prepare_summary(result),
    }
    payload["project_source_roots"] = _existing_session_source_roots(runner)
    if marker is not None:
        _write_prepare_marker(
            marker,
            {
                "ok": True,
                "project_id": config.project_id,
                "session_id": config.session_id,
                "sources": list(config.sources),
                "source_roots": list(config.source_roots),
            },
        )
        payload["marker"] = str(marker)
    _log(payload)
    return payload


def _confirm_existing_source_roots(
    *,
    config,
    runner: EonaCliRunner,
    stdin: TextIO,
    stderr: TextIO,
) -> dict[str, object] | None:
    existing_roots = _existing_session_source_roots(runner)
    if not existing_roots:
        return None
    requested_roots = list(config.source_roots or config.sources)
    if _parse_bool(os.environ.get("EONA_FORCE_APPEND", "0")) or _parse_bool(os.environ.get("EONA_MCP_CONFIRM_APPEND", "0")):
        return None

    skip_reason = "existing_session_sources"
    summary = (
        "Skipped source preparation because the existing project session already has source roots. "
        "Bootstrap does not append or refresh sources in an existing project session by default."
    )
    return {
        "ok": True,
        "operation": "mcp_prepare",
        "status": "skipped",
        "skip_reason": skip_reason,
        "project_id": config.project_id,
        "session_id": config.session_id,
        "sources": list(config.sources),
        "source_roots": list(config.source_roots),
        "existing_source_roots": existing_roots,
        "requested_source_roots": requested_roots,
        "summary": summary,
        "hint": "Set EONA_FORCE_APPEND=1 to force bootstrap to append/refresh these sources, or use the MCP append/refresh tools after bootstrap.",
    }


def _existing_session_source_roots(runner: EonaCliRunner) -> list[str]:
    try:
        payload = runner.list_session_sources()
    except (FileNotFoundError, EonaCliInvocationError):
        return []
    result = payload.get("result")
    if not isinstance(result, dict):
        return []
    source_roots = result.get("source_roots")
    if not isinstance(source_roots, list):
        sources = result.get("sources")
        if not isinstance(sources, list):
            return []
        return [
            str(source.get("source_root") or source.get("source_root_text") or "").strip()
            for source in sources
            if isinstance(source, dict) and str(source.get("source_root") or source.get("source_root_text") or "").strip()
        ]
    return [str(root).strip() for root in source_roots if str(root).strip()]


def _prepare_summary(result: dict[str, object]) -> dict[str, object]:
    add_result = result.get("result") if isinstance(result.get("result"), dict) else {}
    source_payloads = add_result.get("sources") if isinstance(add_result.get("sources"), list) else []
    prepared_sources: list[dict[str, object]] = []
    followup_count = 0
    for source in source_payloads:
        if not isinstance(source, dict):
            continue
        issues = source.get("issues") if isinstance(source.get("issues"), list) else []
        followup_count += len(issues)
        source_summary: dict[str, object] = {
            "source": source.get("source"),
            "ok": bool(source.get("ok", False)),
            "status": source.get("status"),
            "file_count": int(source.get("file_count") or 0),
            "photo_count": int(source.get("photo_count") or 0),
        }
        run_id = source.get("run_id")
        if run_id:
            source_summary["run_id"] = run_id
        prepared_sources.append(source_summary)

    summary = str(result.get("summary") or "").strip()
    if not summary:
        source_count = int(add_result.get("source_count") or len(prepared_sources))
        photo_count = int(add_result.get("photo_count") or sum(int(item.get("photo_count") or 0) for item in prepared_sources))
        summary = f"Prepared {source_count} source(s); {photo_count} photo path(s) available."

    payload: dict[str, object] = {
        "summary": summary,
        "source_count": int(add_result.get("source_count") or len(prepared_sources)),
        "photo_count": int(add_result.get("photo_count") or sum(int(item.get("photo_count") or 0) for item in prepared_sources)),
        "stale_path_count": int(add_result.get("stale_path_count") or 0),
    }
    if prepared_sources:
        payload["prepared_sources"] = prepared_sources
    if followup_count:
        payload["followup_count"] = followup_count
    return payload


def _prepare_marker_path(config, *, marker_dir: Path | None) -> Path | None:
    if marker_dir is None:
        return None
    encoded = json.dumps(
        {
            "session_id": config.session_id,
            "sources": list(config.sources),
            "source_roots": list(config.source_roots),
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return marker_dir / f"{hashlib.sha256(encoded).hexdigest()[:24]}.json"


def _prepare_skip_marker_path(config, *, install_root: Path | None = None) -> Path | None:
    marker_root = install_root
    if marker_root is None:
        install_root_text = os.environ.get("EONA_MCP_INSTALL_ROOT", "").strip()
        marker_root = Path(install_root_text).expanduser().resolve() if install_root_text else None
    if marker_root is None:
        return None
    return marker_root.expanduser().resolve() / ".eona-mcp-prepare-skipped"


def _write_prepare_marker(marker: Path, payload: dict[str, object]) -> None:
    marker.parent.mkdir(parents=True, exist_ok=True)
    tmp_marker = marker.with_suffix(".tmp")
    tmp_marker.write_text(json.dumps(payload, sort_keys=True) + "\n", encoding="utf-8")
    tmp_marker.replace(marker)


def _parse_bool(value: str) -> bool:
    return str(value).strip().lower() not in {"0", "false", "no", "off"}


def _human_color(code: str) -> str:
    if sys.stderr.isatty() and not os.environ.get("NO_COLOR"):
        return f"\033[{code}m"
    return ""


def _display_path(path: object) -> str:
    text = str(path or "").strip()
    if not text:
        return text
    try:
        home = str(Path.home())
        if text == home:
            return "~"
        if text.startswith(home + os.sep):
            return "~/" + text[len(home) + 1 :]
    except RuntimeError:
        pass
    return text


def _print_project_sources_header() -> None:
    global _PROJECT_SOURCES_HEADER_PRINTED
    if _PROJECT_SOURCES_HEADER_PRINTED:
        return
    _PROJECT_SOURCES_HEADER_PRINTED = True
    print("\n[PROJECT SOURCES]\n", file=sys.stderr, flush=True)
    if _parse_bool(os.environ.get("EONA_FORCE_APPEND", "0")):
        print(f"{_human_color('33')}EONA_FORCE_APPEND=1{_human_color('0')}", file=sys.stderr, flush=True)


def _log_prepare_environment(config) -> None:
    if str(os.environ.get("EONA_MCP_PREPARE_OUTPUT", "")).strip().lower() == "json":
        return
    _print_project_sources_header()


def _log(payload: dict[str, object]) -> None:
    if str(os.environ.get("EONA_MCP_PREPARE_OUTPUT", "")).strip().lower() == "json":
        print(json.dumps(payload, sort_keys=True), file=sys.stderr, flush=True)
        return
    if payload.get("ok") is False:
        print(f"[mcp_prepare] ERROR: {payload.get('summary') or 'Project preparation failed.'}", file=sys.stderr, flush=True)
        return

    green = _human_color("32")
    cyan = _human_color("36")
    reset = _human_color("0")
    orange = _human_color("33")
    _print_project_sources_header()

    status = str(payload.get("status") or "").strip()
    summary = str(payload.get("summary") or "").strip()
    prepared_sources = payload.get("prepared_sources")
    prepared_paths: set[str] = set()
    if isinstance(prepared_sources, list):
        for source in prepared_sources:
            if not isinstance(source, dict):
                continue
            source_path = str(source.get("source") or "").strip()
            if source_path:
                prepared_paths.add(source_path)
            file_count = int(source.get("file_count") or 0)
            source_status = str(source.get("status") or "").strip()
            print(f"{green}+{reset}{cyan}{_display_path(source_path)}{reset}", file=sys.stderr, flush=True)
            status_suffix = f" {green}completed{reset}" if source_status else ""
            print(f"{file_count} files indexed{status_suffix}", file=sys.stderr, flush=True)

    existing_roots = payload.get("existing_source_roots")
    requested_roots = payload.get("requested_source_roots")
    project_source_roots = payload.get("project_source_roots")
    current_source_roots = payload.get("current_source_roots")
    if isinstance(project_source_roots, list):
        all_roots = [str(root).strip() for root in project_source_roots if str(root).strip()]
    elif isinstance(current_source_roots, list):
        all_roots = [str(root).strip() for root in current_source_roots if str(root).strip()]
    elif isinstance(existing_roots, list):
        all_roots = [str(root).strip() for root in existing_roots if str(root).strip()]
    else:
        all_roots = []

    skip_reason = str(payload.get("skip_reason") or "").strip()
    retained_roots = [root for root in all_roots if root not in prepared_paths]
    if skip_reason == "no_sources_configured":
        print("no bootstrap source input; skipping source preparation", file=sys.stderr, flush=True)
    if retained_roots:
        if prepared_paths:
            print("", file=sys.stderr, flush=True)
        for root in retained_roots:
            print(f"{cyan}{_display_path(root)}{reset}", file=sys.stderr, flush=True)
        print(f"{len(all_roots)} total sources attached", file=sys.stderr, flush=True)
        print("", file=sys.stderr, flush=True)
    elif not prepared_paths and skip_reason != "no_sources_configured":
        print("none", file=sys.stderr, flush=True)

    if skip_reason == "existing_session_sources":
        requested_blocked: list[str] = []
        if isinstance(requested_roots, list):
            requested_blocked = [str(item).strip() for item in requested_roots if str(item).strip()]
        if requested_blocked:
            print("requested sources were not appended:", file=sys.stderr, flush=True)
            for root in requested_blocked:
                print(f"  {orange}{_display_path(root)}{reset}", file=sys.stderr, flush=True)
    elif skip_reason == "no_sources_configured":
        pass
    elif status == "skipped" and summary:
        print(summary, file=sys.stderr, flush=True)
    elif not prepared_paths and summary:
        print(summary, file=sys.stderr, flush=True)

    hint = str(payload.get("hint") or "").strip()
    if hint:
        lines = hint.splitlines()
        if lines and lines[0] == "No source folders are attached.":
            print(f"{orange}{lines[0]}{reset}", file=sys.stderr, flush=True)
            for line in lines[1:]:
                print(line, file=sys.stderr, flush=True)
        else:
            print(hint.replace("EONA_FORCE_APPEND=1", f"{orange}EONA_FORCE_APPEND=1{reset}"), file=sys.stderr, flush=True)


if __name__ == "__main__":
    raise SystemExit(main())
